export const NAV_FETCH_START = 'NAV_FETCH_START';
export const NAV_FETCH_FAILED = 'NAV_FETCH_FAILED';
export const NAV_FETCH_SUCCESS = 'NAV_FETCH_SUCCESS';

export const NAV_PAGE_LOAD_START = 'NAV_PAGE_LOAD_START';
export const NAV_PAGE_LOAD_FAILED = 'NAV_PAGE_LOAD_FAILED';
export const NAV_PAGE_LOAD_SUCCESS = 'NAV_PAGE_LOAD_SUCCESS';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
