export const NAV_FETCH_START = 'NAV_FETCH_START';
export const NAV_FETCH_FAILED = 'NAV_FETCH_FAILED';
export const NAV_FETCH_SUCCESS = 'NAV_FETCH_SUCCESS';

export const PAGE_FETCH_START = 'PAGE_FETCH_START';
export const PAGE_FETCH_FAILED = 'PAGE_FETCH_FAILED';
export const PAGE_FETCH_SUCCESS = 'PAGE_FETCH_SUCCESS';
export const PAGE_SET_LOCALE = 'PAGE_SET_LOCALE';



export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOCALES_FETCH_START = 'LOCALES_FETCH_START';
export const LOCALES_FETCH_FAILED = 'LOCALES_FETCH_FAILED';
export const LOCALES_FETCH_SUCCESS = 'LOCALES_FETCH_SUCCESS';
